blank_issues_enabled: false
contact_links:
  - name: 💬 Dan's Mods discord
    url: https://discord.gg/wuSsgKwAKv
    about: Ask for help or get more info on Discord. --- Server link --->
  - name: 💡 Feature requests / suggestions
    url: https://discord.gg/wuSsgKwAKv
    about: Please use the discord server to suggest stuff. --- Server link --->
