name: 'Build Mod'
on:
  push:
    branches:
      - '[0-9]**'
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.forge/**'
      - LICENSE
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Load Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Build
        run: 'chmod 777 gradlew'

      - name: Build with Gradle
        id: build
        env: 
          USE_ALPHAS: true
        run: './gradlew setupGithubActions build --max-workers=1'
